### ISSUE TITLE
Global styles defined in 'styles.css' are only applied during compilation and not after an edit reload

### ISSUE THREAD

**Issue by Achilles1515** [alexzuza/ng-run-issue-tracker#14]
Not sure if the issue title is exactly correct...

1) Open a new ng-run demo.
2) Edit the "styles.css" file and add the following:
```css
/* Write your global styles here */
h2 {
  color: red;
}
```

Following the preview reload from the edit, I would expect the "Hello Angular" text to change to red, but it stays as the default value. Even manually clicking the preview refresh button does not change the text to red. But, toggling between Ivy/View Engine will update the color.
